# Generated by Django 2.1.4 on 2019-01-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190109_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='japan', max_length=32, verbose_name='題名'),
            preserve_default=False,
        ),
    ]
